const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    const [deployer] = await ethers.getSigners();
    console.log("\n⚡ ArcTreasury Deployment");
    console.log("========================================");
    console.log("  Deployer:", deployer.address);

    const balance = await ethers.provider.getBalance(deployer.address);
    console.log("  Balance:", ethers.formatUnits(balance, 6), "USDC (gas token)");
    console.log("========================================\n");

    // ── 1. Deploy Mock Tokens ──────────────────────────────────

    const MockERC20 = await ethers.getContractFactory("MockERC20");

    console.log("Deploying MockUSDC...");
    const usdc = await MockERC20.deploy("Mock USDC", "USDC");
    await usdc.waitForDeployment();
    const usdcAddr = await usdc.getAddress();
    console.log("  MockUSDC deployed to:", usdcAddr);

    console.log("Deploying MockEURC...");
    const eurc = await MockERC20.deploy("Mock EURC", "EURC");
    await eurc.waitForDeployment();
    const eurcAddr = await eurc.getAddress();
    console.log("  MockEURC deployed to:", eurcAddr);

    console.log("Deploying MockUSYC...");
    const usyc = await MockERC20.deploy("Mock USYC", "USYC");
    await usyc.waitForDeployment();
    const usycAddr = await usyc.getAddress();
    console.log("  MockUSYC deployed to:", usycAddr);

    // ── 2. Deploy ArcTreasury ──────────────────────────────────

    const stableFXRouter = "0x0000000000000000000000000000000000000001"; // placeholder
    const usycVault = "0x0000000000000000000000000000000000000002";      // placeholder
    const agentAddress = deployer.address; // deployer = agent for hackathon

    console.log("\nDeploying ArcTreasury...");
    const ArcTreasury = await ethers.getContractFactory("ArcTreasury");
    const treasury = await ArcTreasury.deploy(
        usdcAddr,
        eurcAddr,
        usycAddr,
        stableFXRouter,
        usycVault,
        agentAddress
    );
    await treasury.waitForDeployment();
    const treasuryAddr = await treasury.getAddress();
    console.log("  ArcTreasury deployed to:", treasuryAddr);

    // ── 3. Mint tokens to deployer ─────────────────────────────

    const DECIMALS = 18n;
    const mintUSDC = 500_000n * 10n ** DECIMALS;
    const mintEURC = 200_000n * 10n ** DECIMALS;
    const mintUSYC = 300_000n * 10n ** DECIMALS;

    console.log("\nMinting tokens to deployer...");
    await (await usdc.mint(deployer.address, mintUSDC)).wait();
    console.log("  500,000 USDC minted");
    await (await eurc.mint(deployer.address, mintEURC)).wait();
    console.log("  200,000 EURC minted");
    await (await usyc.mint(deployer.address, mintUSYC)).wait();
    console.log("  300,000 USYC minted");

    // ── 4. Approve ArcTreasury to spend tokens ─────────────────

    console.log("\nApproving ArcTreasury to spend tokens...");
    await (await usdc.approve(treasuryAddr, mintUSDC)).wait();
    console.log("  USDC approved");
    await (await eurc.approve(treasuryAddr, mintEURC)).wait();
    console.log("  EURC approved");
    await (await usyc.approve(treasuryAddr, mintUSYC)).wait();
    console.log("  USYC approved");

    // ── 5. Deposit into treasury ───────────────────────────────

    const depUSDC = 250_000n * 10n ** DECIMALS;
    const depEURC = 85_000n * 10n ** DECIMALS;
    const depUSYC = 150_000n * 10n ** DECIMALS;

    console.log("\nDepositing tokens into ArcTreasury...");
    await (await treasury.deposit(usdcAddr, depUSDC)).wait();
    console.log("  250,000 USDC deposited");
    await (await treasury.deposit(eurcAddr, depEURC)).wait();
    console.log("  85,000 EURC deposited");
    await (await treasury.deposit(usycAddr, depUSYC)).wait();
    console.log("  150,000 USYC deposited");

    // ── 6. Copy ABI ────────────────────────────────────────────

    const abiSourcePath = path.join(
        __dirname, "..", "artifacts", "contracts",
        "ArcTreasury.sol", "ArcTreasury.json"
    );
    const abiDestDir = path.join(__dirname, "..", "agent", "abi");
    const abiDestPath = path.join(abiDestDir, "Treasury.json");

    if (!fs.existsSync(abiDestDir)) {
        fs.mkdirSync(abiDestDir, { recursive: true });
    }

    const artifact = JSON.parse(fs.readFileSync(abiSourcePath, "utf8"));
    fs.writeFileSync(abiDestPath, JSON.stringify(artifact.abi, null, 2));
    console.log("\nABI copied to:", abiDestPath);

    // ── 7. Update agent/.env ───────────────────────────────────

    const agentEnvPath = path.join(__dirname, "..", "agent", ".env");
    const envLines = [
        `# Auto-generated by deploy script at ${new Date().toISOString()}`,
        `ARC_RPC_URL=https://rpc.testnet.arc.network`,
        `CHAIN_ID=5042002`,
        `PRIVATE_KEY=${process.env.PRIVATE_KEY}`,
        `TREASURY_CONTRACT=${treasuryAddr}`,
        `USDC_ADDRESS=${usdcAddr}`,
        `EURC_ADDRESS=${eurcAddr}`,
        `USYC_ADDRESS=${usycAddr}`,
        `STORK_WS_URL=wss://stork-ws.example.com`,
        `STORK_API_KEY=demo`,
    ];
    fs.writeFileSync(agentEnvPath, envLines.join("\n") + "\n");
    console.log("agent/.env updated with deployed addresses");

    // ── 8. Update root .env ────────────────────────────────────

    const rootEnvPath = path.join(__dirname, "..", ".env");
    let rootEnv = "";
    if (fs.existsSync(rootEnvPath)) {
        rootEnv = fs.readFileSync(rootEnvPath, "utf8");
    }
    // Update or append address lines
    const replacements = {
        TREASURY_ADDRESS: treasuryAddr,
        USDC_ADDRESS: usdcAddr,
        EURC_ADDRESS: eurcAddr,
        USYC_ADDRESS: usycAddr,
    };
    for (const [key, val] of Object.entries(replacements)) {
        const regex = new RegExp(`^${key}=.*$`, "m");
        if (regex.test(rootEnv)) {
            rootEnv = rootEnv.replace(regex, `${key}=${val}`);
        } else {
            rootEnv += `\n${key}=${val}`;
        }
    }
    fs.writeFileSync(rootEnvPath, rootEnv);
    console.log("Root .env updated with deployed addresses");

    // ── 9. Summary ─────────────────────────────────────────────

    console.log("\n========================================");
    console.log("       ⚡ DEPLOYMENT COMPLETE ⚡");
    console.log("========================================");
    console.log("  Network:       Arc Testnet (5042002)");
    console.log("  Deployer:     ", deployer.address);
    console.log("  ────────────────────────────────────");
    console.log("  MockUSDC:     ", usdcAddr);
    console.log("  MockEURC:     ", eurcAddr);
    console.log("  MockUSYC:     ", usycAddr);
    console.log("  ArcTreasury:  ", treasuryAddr);
    console.log("  ────────────────────────────────────");
    console.log("  StableFX:     ", stableFXRouter, "(placeholder)");
    console.log("  USYC Vault:   ", usycVault, "(placeholder)");
    console.log("  Agent:        ", agentAddress, "(= deployer)");
    console.log("  ────────────────────────────────────");
    console.log("  Treasury USDC: 250,000");
    console.log("  Treasury EURC:  85,000");
    console.log("  Treasury USYC: 150,000");
    console.log("========================================\n");
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("\n❌ Deployment failed:", error);
        process.exit(1);
    });
